### ISSUE TITLE
"KeyError: 'applicant_id'" when running classifiers

### ISSUE THREAD

**Issue by Irio** [datasciencebr/rosie#25]
Running on my machine this morning, an exception is raised. Probably caused by recent changes in Chamber of Deputies' XMLs.

```
$ python rosie.py run ~/Desktop/serenata-data
2017-01-27 10:43:17 Creating the CSV file
2017-01-27 10:43:17 Reading the XML file
2017-01-27 10:43:17 Writing record #2,796 to the CSV
2017-01-27 10:43:17 Done!
2017-01-27 10:43:17 Creating the CSV file
2017-01-27 10:43:17 Reading the XML file
2017-01-27 10:45:26 Writing record #342,077 to the CSV
2017-01-27 10:45:26 Done!
2017-01-27 10:45:26 Creating the CSV file
2017-01-27 10:45:26 Reading the XML file
2017-01-27 11:03:38 Writing record #2,404,938 to the CSV
2017-01-27 11:03:38 Done!
Merging all datasets…
Loading current-year.xz…
Loading last-year.xz…
Loading previous-years.xz…
Dropping rows without document_value or reimbursement_number…
Grouping dataset by applicant_id, document_id and year…
Gathering all reimbursement numbers together…
Summing all net values together…
Summing all reimbursement values together…
Generating the new dataset…
Casting changes to a new DataFrame…
Writing it to file…
Done.
/Users/irio/Code/serenata/rosie/rosie/dataset.py:52: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  dataset['cnpj'] = dataset['cnpj'].str.replace(r'\D', '')
Traceback (most recent call last):
  File "/Users/irio/anaconda3/envs/serenata_rosie/lib/python3.5/site-packages/pandas/indexes/base.py", line 2134, in get_loc
    return self._engine.get_loc(key)
  File "pandas/index.pyx", line 132, in pandas.index.IndexEngine.get_loc (pandas/index.c:4433)
  File "pandas/index.pyx", line 154, in pandas.index.IndexEngine.get_loc (pandas/index.c:4279)
  File "pandas/src/hashtable_class_helper.pxi", line 732, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:13742)
  File "pandas/src/hashtable_class_helper.pxi", line 740, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:13696)
KeyError: 'applicant_id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "rosie.py", line 36, in <module>
    command()
  File "rosie.py", line 23, in run
    rosie.main(target_directory)
  File "/Users/irio/Code/serenata/rosie/rosie/__init__.py", line 65, in main
    Rosie(dataset, target_directory).run_classifiers()
  File "/Users/irio/Code/serenata/rosie/rosie/__init__.py", line 30, in run_classifiers
    self.predict(model, irregularity)
  File "/Users/irio/Code/serenata/rosie/rosie/__init__.py", line 56, in predict
    y = model.predict(self.dataset)
  File "/Users/irio/Code/serenata/rosie/rosie/traveled_speeds_classifier.py", line 35, in predict
    _X = self.__aggregate_dataset(_X)
  File "/Users/irio/Code/serenata/rosie/rosie/traveled_speeds_classifier.py", line 52, in __aggregate_dataset
    right_on=self.AGG_KEYS)
  File "/Users/irio/anaconda3/envs/serenata_rosie/lib/python3.5/site-packages/pandas/tools/merge.py", line 61, in merge
    copy=copy, indicator=indicator)
  File "/Users/irio/anaconda3/envs/serenata_rosie/lib/python3.5/site-packages/pandas/tools/merge.py", line 543, in __init__
    self.join_names) = self._get_merge_keys()
  File "/Users/irio/anaconda3/envs/serenata_rosie/lib/python3.5/site-packages/pandas/tools/merge.py", line 810, in _get_merge_keys
    right_keys.append(right[rk]._values)
  File "/Users/irio/anaconda3/envs/serenata_rosie/lib/python3.5/site-packages/pandas/core/frame.py", line 2059, in __getitem__
    return self._getitem_column(key)
  File "/Users/irio/anaconda3/envs/serenata_rosie/lib/python3.5/site-packages/pandas/core/frame.py", line 2066, in _getitem_column
    return self._get_item_cache(key)
  File "/Users/irio/anaconda3/envs/serenata_rosie/lib/python3.5/site-packages/pandas/core/generic.py", line 1386, in _get_item_cache
    values = self._data.get(item)
  File "/Users/irio/anaconda3/envs/serenata_rosie/lib/python3.5/site-packages/pandas/core/internals.py", line 3543, in get
    loc = self.items.get_loc(item)
  File "/Users/irio/anaconda3/envs/serenata_rosie/lib/python3.5/site-packages/pandas/indexes/base.py", line 2136, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/index.pyx", line 132, in pandas.index.IndexEngine.get_loc (pandas/index.c:4433)
  File "pandas/index.pyx", line 154, in pandas.index.IndexEngine.get_loc (pandas/index.c:4279)
  File "pandas/src/hashtable_class_helper.pxi", line 732, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:13742)
  File "pandas/src/hashtable_class_helper.pxi", line 740, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:13696)
KeyError: 'applicant_id'
```

**Comment by cuducos** [comment]
Lines 51 and 52 are:

```python
        dataset = dataset.query(is_in_brazil)
        dataset['cnpj'] = dataset['cnpj'].str.replace(r'\D', '')
```

Probably `.query(…)` returns a slice and Pandas is complaining about line 52 (replacing a string in a slice). Does it worth it to change the order: first we format CNPJ (in line 51) and then (line 52) we remove the non-Brazilian companies?

**Comment by jtemporal** [comment]
So, I ran a few tests today in an attempt fix this bug. Switching the order of the lines as mentioned by @cuducos in the comment above would not work in the Digital Ocean droplet that I was using. It gave a `MemoryError` ([traceback can be found here](https://gist.github.com/jtemporal/cbede5ff180aeba2ab42f1573c7aab27)) 

I tried locally to run in ipython what @Irio traceback showed:

> A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

The results I got can be found [here](https://gist.github.com/jtemporal/f641cfe19b8d45a0f0bff524f7f077bf)

The problem with `.loc[row_indexer,col_dexer] = value` is that the replace (`replace(r'\D', '')`) we need to do does not seem to work.

Any suggestions?

**Comment by cuducos** [comment]
> The problem with `.loc[row_indexer,col_dexer] = value` is that the replace (`replace(r'\D', '')`) we need to do does not seem to work.

Can you share the code you tried? Maybe there are other ways use the `re.replace` with your code.

**Comment by jtemporal** [comment]
@cuducos 

 The results and code I got can be found [here](https://gist.github.com/jtemporal/f641cfe19b8d45a0f0bff524f7f077bf)

**Comment by cuducos** [comment]
This worked here:

```python
df = pd.read_csv('data/2016-09-03-companies.xz', dtype={'cnpj': np.str}, low_memory=False)
df = df.query(is_in_brazil)
cnpjs = df['cnpj'].copy()
df['cnpj'] = cnpjs.str.replace(r'\D', '')
df.loc[0, 'cnpj']  # '05939467000115'
```

**Comment by Irio** [comment]
@cuducos It serves the same purpose for me.

**Comment by cuducos** [comment]
*UPDATE:* If you're getting this error chances that you don't have enough hardware, not a bug in the source code. So, kudos to #24
